version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drone_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - mydb:/var/lib/mysql
    restart: always

  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel-P.I:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./laravel-P.I:/var/www
      - ./nginx:/etc/nginx/conf.d/

volumes:
  mydb:
