#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('drone_db_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap drone_db and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
